apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-17T14:11:15Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "2024"
  uid: d2ea196e-5cc7-47cc-91dd-e2631e9c1b61
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.105.145.238
  clusterIPs:
  - 10.105.145.238
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32765
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
